title: leomuckley.com # your name (or website title) here
logo: "/images/headshot-circle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <h2>Bio</h2>
  Cork, Ireland
  <br>
  Data Scientist | AI Researcher
  <br>
  MSc Data Science
  <br>
  University of Edinburgh
    
  <br><br>
  <h2>Profile Links</h2>
  <a href="https://github.com/leomuckley/">View My GitHub Profile</a>
  <br>
  <a href="https://www.linkedin.com/in/leo-muckley/">View My LinkedIn Profile</a>
  <br>
  <a href="https://www.kaggle.com/leomuckley/">View My Kaggle Profile</a>
  
  
theme: jekyll-theme-minimal # Github pages theme
google_analytics: UA-186245913-1 # Google Analytics tracking ID
