name: Leo Muckley
markdown: kramdown
# Conversion
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  extensions: fenced_code_blocks
permalink: /blog/:year/:month/:day/:title


