title: leomuckley.com # your name (or website title) here
logo: "/images/headshot-circle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <h2>Bio</h2>
  <br>
  I am Data Scientist from Cork, Ireland. I am currently working on industrial artificla intelligence research for a power management company.
  <br>
  I received a BA in Economics & Mathematical Studies at University College Cork and a MSc in Data Science at the University of Ediburgh.
  <br>
  I have published work at the International Conference on Pattern Recognition and several patents pending based on my research in deep learning and artificial intelligence. 
  <br>
  When I am not doing research or competing in Kaggle competitions, I love to travel, go hiking and practice photography (especially street photography!). 
  
  <br><br>
  <h2>Profile Links</h2>
  <a href="https://github.com/leomuckley/">View My GitHub Profile</a>
  <br>
  <a href="https://www.linkedin.com/in/leo-muckley/">View My LinkedIn Profile</a>
  <br>
  <a href="https://www.kaggle.com/leomuckley/">View My Kaggle Profile</a>
  
  
theme: jekyll-theme-minimal # Github pages theme
google_analytics: UA-186245913-1 # Google Analytics tracking ID
